site_name: FutBoard

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - toc.integrate
  palette:
    - scheme: default
      primary: indigo

nav:
  - Início: index.md
  - Visão do Produto e Projeto:
      - visao-produto/index.md
      - Cliente e Negócio: visao-produto/cenario-atual.md
      - Solução Proposta: visao-produto/solucao-proposta.md
      - Intervenção Social: visao-produto/intervencao-social.md
      - Estratégias de Software: visao-produto/estrategias-esw.md
      - Engenharia de Requisitos: visao-produto/engenharia-requisitos.md
      - Cronograma e Entregas: visao-produto/cronogramas-entregas.md
      - Interação com Cliente: visao-produto/interacao-equipe-cliente.md
  - Lições Aprendidas: licoes-aprendidas.md