site_name: FutBoard

theme:
  name: material
  palette:
    - scheme: default
      primary: custom
      accent: custom
  font:
    text: Inter
    code: Fira Code
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight

markdown_extensions:
  - attr_list
  - md_in_html
  - def_list

extra_css:
  - stylesheets/extra.css

nav:
  - Início: index.md
  - Visão do Produto e Projeto:
      - Cenário Atual do Cliente e Negócio: visao-produto/cenario-atual.md
      - Solução Proposta: visao-produto/solucao-proposta.md
      - Intervenção Social: visao-produto/intervencao-social.md
      - Estratégias de Software: visao-produto/estrategias-esw.md
      - Engenharia de Requisitos: visao-produto/engenharia-requisitos.md
      - Cronograma e Entregas: visao-produto/cronogramas-entregas.md
      - Interação com Cliente: visao-produto/interacao-equipe-cliente.md
  - Atas e Reuniões:
      - Reuniões: atas-reunioes/reunioes.md
  - Lições Aprendidas: licoes-aprendidas.md

